window.CESApi=(()=>{
  let seq=0;
  function execUrl(){const raw=String((window.CES_CONFIG&&window.CES_CONFIG.webAppUrl)||'').trim().replace(/\?.*$/,'').replace(/\/$/,'');if(!/^https:\/\/script\.google\.com\/macros\/s\/[^/]+\/exec$/i.test(raw))throw new Error('Apps Script /exec URL in config.js is invalid');return raw;}
  function isConfigured(){try{execUrl();return true}catch(_){return false}}
  function encodePayload(value){const bytes=new TextEncoder().encode(JSON.stringify(value||[]));let binary='';for(const b of bytes)binary+=String.fromCharCode(b);return btoa(binary).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
  function call(method,...args){return new Promise((resolve,reject)=>{let url;try{url=execUrl()}catch(e){reject(e);return}const cb='CESJSONP_'+Date.now()+'_'+(++seq),script=document.createElement('script'),timeout=Number(window.CES_CONFIG.apiTimeoutMs)||25000;let finished=false,timer;const clean=()=>{if(finished)return;finished=true;clearTimeout(timer);try{delete window[cb]}catch(_){window[cb]=undefined}script.remove()};window[cb]=resp=>{if(finished)return;const ok=resp&&resp.ok,result=resp&&resp.result,error=resp&&resp.error;clean();ok?resolve(result):reject(new Error(error||'Backend error'))};script.onerror=()=>{clean();reject(new Error('Cannot connect to Apps Script. Check /exec deployment and Web App access.'))};const qs=new URLSearchParams({api:'1',method,payload:encodePayload(args),origin:location.origin,callback:cb,_:String(Date.now())});script.src=url+'?'+qs.toString();script.async=true;script.referrerPolicy='no-referrer';timer=setTimeout(()=>{clean();reject(new Error('Apps Script did not respond within '+Math.round(timeout/1000)+' seconds'))},timeout);document.head.appendChild(script);});}
  return{call,isConfigured,execUrl};
})();

const S={token:null,profile:null,bootstrap:null,data:null,settings:null,rows:[],staff:[],contracts:[],files:[],notifyConfig:[],page:'dashboard',dataVersion:'0',syncTimer:null,charts:{trend:null,site:null,status:null,compare:null},activeContractRow:null};
const $=id=>document.getElementById(id);
const money=v=>v===null||v===undefined||Number.isNaN(Number(v))?'—':new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB',maximumFractionDigits:0}).format(Number(v));
const pct=v=>v===null||v===undefined||Number.isNaN(Number(v))?'—':(Number(v)*100).toFixed(1)+'%';
const num=v=>v===null||v===undefined||v===''?'—':new Intl.NumberFormat('en-US',{maximumFractionDigits:1}).format(Number(v));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtDate=v=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'});};
const fmtDateTime=v=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString('th-TH',{dateStyle:'medium',timeStyle:'short'});};
const csvCell=v=>'"'+String(v??'').replace(/"/g,'""')+'"';
const icon=(name)=>`<svg><use href="#i-${name}"/></svg>`;
function showLoading(v){$('loading').classList.toggle('hidden',!v)}
function toast(msg){$('toast').textContent=msg;$('toast').classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.add('hidden'),3600)}
function errMsg(e){return(e&&e.message)||String(e)}
function statusClass(s){s=String(s||'').toLowerCase();return s==='active'?'st-active':s==='defective'?'st-defective':s==='decommission'?'st-decommission':s==='warranty'?'st-warranty':'st-other'}
function deltaClass(v){return v===null||v===undefined?'flat':Number(v)>0?'up':Number(v)<0?'down':'flat'}
function initialOf(name){const x=String(name||'U').trim();return x?x.charAt(0).toUpperCase():'U'}
function setSyncState(text,sub,state='orange'){ $('syncLabel').textContent=text;$('syncSub').textContent=sub||'';$('syncDot').className='sync-dot status-'+state;const dot=$('liveStatusPill').querySelector('.status-dot');dot.className='status-dot '+(state==='green'?'green':state==='red'?'red':'orange');$('liveStatusPill').querySelector('span:last-child').textContent=state==='green'?'LIVE':state==='red'?'SYNC ERROR':'CHECKING'; }
function fillSelect(id,values,placeholder){const el=$(id),keep=el.value;el.innerHTML=`<option value="">${esc(placeholder)}</option>`+(values||[]).map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');if((values||[]).includes(keep))el.value=keep;}
function fillYear(id,years,selected){$(id).innerHTML=(years||[]).map(y=>`<option value="${y}">${y}</option>`).join('');if(selected)$(id).value=String(selected)}
function daysUntil(v){if(!v)return null;const d=new Date(v);if(Number.isNaN(d.getTime()))return null;return Math.floor((d-new Date())/86400000)}
function statusBadge(s){return `<span class="status ${statusClass(s)}">${esc(s||'Other')}</span>`}
function actionButton(action,id,title,iconName){return `<button class="action-btn" data-action="${action}" data-id="${esc(id)}" title="${esc(title)}">${icon(iconName)}</button>`}

async function boot(){
  bindEvents();$('signInBtn').disabled=false;$('backendStatus').textContent=CESApi.isConfigured()?'Backend ready':'Backend URL missing';
  const tok=sessionStorage.getItem('ces_token');if(!tok)return;try{S.token=tok;showLoading(true);await loadBootstrap(true);showApp();await loadDashboard();startAutoSync()}catch(_){sessionStorage.removeItem('ces_token');S.token=null}finally{showLoading(false)}
}
function bindEvents(){
  $('loginForm').addEventListener('submit',login);$('logoutBtn').onclick=logout;$('viewProfileBtn').onclick=openProfile;$('profileForm').addEventListener('submit',saveProfile);
  document.querySelectorAll('.nav-btn[data-page]').forEach(b=>b.onclick=()=>switchPage(b.dataset.page));
  $('sideCollapseBtn').onclick=()=>toggleSidebar();$('mobileMenuBtn').onclick=()=>{$('sidebar').classList.toggle('mobile-open')};
  $('profileBtn').onclick=e=>{e.stopPropagation();$('profileMenu').classList.toggle('hidden')};document.addEventListener('click',e=>{if(!$('profileMenu').contains(e.target)&&!$('profileBtn').contains(e.target))$('profileMenu').classList.add('hidden')});
  $('topSyncBtn').onclick=()=>checkSync(true);$('notificationBtn').onclick=openAlertCenter;document.querySelectorAll('[data-cmd]').forEach(b=>b.onclick=()=>handleCommand(b.dataset.cmd));document.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>handleExport(b.dataset.export));
  $('advancedToggle').onclick=()=>{$('advancedFilters').classList.toggle('hidden');$('advancedToggle').innerHTML=icon('filter')+($('advancedFilters').classList.contains('hidden')?'Advanced':'Hide advanced')};$('resetBtn').onclick=resetFilters;
  const filterIds=['compareYear','year','site','vendor','hospital','group','modality','model','status','maType','quality','scenario','sourceSheet','priceAvailability','dataReady','risk','ageBand','contractWindow','movement','sortBy'];filterIds.forEach(id=>$(id).addEventListener('change',loadDashboardSafe));['priceMin','priceMax','changeMinPct','changeMaxPct'].forEach(id=>{let t;$(id).addEventListener('input',()=>{clearTimeout(t);t=setTimeout(loadDashboardSafe,400)})});let st;$('search').addEventListener('input',()=>{clearTimeout(st);st=setTimeout(loadDashboardSafe,300)});
  $('globalSearch').addEventListener('input',globalSearchChanged);document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('globalSearch').focus();$('globalSearch').select();}});
  $('equipmentBody').addEventListener('click',equipmentAction);$('priorityBody').addEventListener('click',equipmentAction);$('vendorMovement').addEventListener('click',e=>{const b=e.target.closest('[data-vendor]');if(b)openCompareVendor(b.dataset.vendor)});
  document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).classList.add('hidden'));document.querySelectorAll('.modal-backdrop').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.add('hidden')}));
  $('editYear').addEventListener('change',syncEditPrice);$('editForm').addEventListener('submit',saveEdit);
  $('contractSite').addEventListener('change',loadSiteContracts);$('contractVendor').addEventListener('change',loadSiteContracts);$('contractYear').addEventListener('change',loadSiteContracts);$('contractSearch').addEventListener('input',renderContracts);$('contractResetBtn').onclick=()=>{['contractSite','contractVendor'].forEach(id=>$(id).value='');$('contractSearch').value='';loadSiteContracts()};$('contractBody').addEventListener('click',contractAction);$('uploadTopBtn').onclick=()=>openUpload();$('uploadForm').addEventListener('submit',startUpload);window.addEventListener('message',e=>{if(e.data&&e.data.type==='CES_CONTRACT_UPLOAD_COMPLETE'){toast('Contract file uploaded');loadSiteContracts();}});
  $('addStaffBtn').onclick=()=>openUserModal();$('reloadStaffBtn').onclick=loadUsers;$('staffSearch').addEventListener('input',renderUsers);$('staffBody').addEventListener('click',e=>{const b=e.target.closest('[data-user]');if(b)openUserModal(b.dataset.user)});$('staffForm').addEventListener('submit',saveUser);$('userExportBtn').onclick=exportUsers;
  $('settingsRefreshBtn').onclick=loadSettings;$('localSyncSec').addEventListener('change',()=>{localStorage.setItem('ces_sync_sec',$('localSyncSec').value);startAutoSync();toast('Live sync interval updated')});$('saveSettingsBtn').onclick=saveSettings;$('saveAlertSettingsBtn').onclick=saveSettings;$('readinessBtn').onclick=viewReadiness;$('rebuildBtn').onclick=rebuildData;$('notifyConfigBody').addEventListener('click',notificationConfigAction);$('notifyForm').addEventListener('submit',saveNotificationConfig);$('testNotifyBtn').onclick=testNotification;$('runNotifyNowBtn').onclick=runNotificationNow;
  window.addEventListener('focus',()=>{if(S.token)checkSync(true)});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&S.token)checkSync(true)});window.addEventListener('online',()=>{if(S.token)checkSync(true)});
}
async function login(e){e.preventDefault();$('loginError').classList.add('hidden');const staffId=$('staffId').value.trim();if(!staffId)return;try{$('signInBtn').disabled=true;$('signInBtn').textContent='Checking…';const r=await CESApi.call('login',{staffId});S.token=r.token;S.profile=r.profile;sessionStorage.setItem('ces_token',S.token);showApp();showLoading(true);await loadBootstrap(false);await loadDashboard();startAutoSync();toast('Sign in successful')}catch(err){$('loginError').textContent=errMsg(err);$('loginError').classList.remove('hidden')}finally{$('signInBtn').disabled=false;$('signInBtn').textContent='Sign in';showLoading(false)}}
function showApp(){$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');if(localStorage.getItem('ces_sidebar')==='collapsed')$('sidebar').classList.add('collapsed')}
async function logout(){try{if(S.token)await CESApi.call('logout',S.token)}catch(_){}clearInterval(S.syncTimer);sessionStorage.removeItem('ces_token');location.reload()}
function toggleSidebar(){const c=$('sidebar').classList.toggle('collapsed');localStorage.setItem('ces_sidebar',c?'collapsed':'open')}

async function loadBootstrap(keepFilters){const old=keepFilters?getFilterState():null;S.bootstrap=await CESApi.call('bootstrap',S.token);S.profile=S.bootstrap.profile;S.dataVersion=String(S.bootstrap.dataVersion);populateFilters();if(old)restoreFilters(old);updateProfileUi();$('userNav').classList.toggle('hidden',!S.profile.canManageAccess);$('openDriveTopBtn').href=window.CES_CONFIG.contractDriveUrl;$('openDriveBtn').href=window.CES_CONFIG.contractDriveUrl;}
function populateFilters(){const b=S.bootstrap, f=b.filters||{};fillYear('compareYear',b.years,b.defaults.compareYear);fillYear('year',b.years,b.defaults.year);fillYear('contractYear',b.years,b.defaults.year);fillSelect('site',f.sites,'All allowed');fillSelect('contractSite',f.sites,'All allowed');fillSelect('uSite',f.sites,'Select Site');fillSelect('vendor',f.vendors,'All vendors');fillSelect('contractVendor',f.vendors,'All vendors');fillSelect('hospital',f.hospitals,'All hospitals');fillSelect('group',f.groups,'All groups');fillSelect('modality',f.modalities,'All equipment');fillSelect('model',f.models,'All models');fillSelect('status',f.statuses,'All status');fillSelect('maType',f.maTypes,'All MA type');fillSelect('quality',f.quality,'All quality');fillSelect('scenario',f.scenarios,'All scenarios');fillSelect('sourceSheet',f.sourceSheets,'All sources');fillSelect('risk',f.risks,'All risks');fillSelect('ageBand',f.ageBands,'All ages');fillSelect('contractWindow',f.contractWindows,'Any date');fillSelect('movement',f.movements,'Any movement');fillSelect('sortBy',f.sortOptions,'Default sort');}
function getFilterState(){return{compareYear:+$('compareYear').value,year:+$('year').value,site:$('site').value,vendor:$('vendor').value,hospital:$('hospital').value,group:$('group').value,modality:$('modality').value,model:$('model').value,status:$('status').value,maType:$('maType').value,quality:$('quality').value,scenario:$('scenario').value,sourceSheet:$('sourceSheet').value,priceAvailability:$('priceAvailability').value,dataReady:$('dataReady').value,risk:$('risk').value,ageBand:$('ageBand').value,contractWindow:$('contractWindow').value,movement:$('movement').value,priceMin:$('priceMin').value,priceMax:$('priceMax').value,changeMinPct:$('changeMinPct').value,changeMaxPct:$('changeMaxPct').value,sortBy:$('sortBy').value,search:$('search').value.trim()};}
function restoreFilters(f){Object.entries(f||{}).forEach(([k,v])=>{const el=$(k);if(!el||v===null||v===undefined)return;if(el.tagName==='INPUT'||[...el.options].some(o=>o.value===String(v)))el.value=String(v)})}
function resetFilters(){['site','vendor','hospital','group','modality','model','status','maType','quality','scenario','sourceSheet','priceAvailability','dataReady','risk','ageBand','contractWindow','movement','priceMin','priceMax','changeMinPct','changeMaxPct','search'].forEach(id=>$(id).value='');$('compareYear').value=String(S.bootstrap.defaults.compareYear);$('year').value=String(S.bootstrap.defaults.year);loadDashboardSafe()}
function activeFilterCount(){const f=getFilterState();return Object.entries(f).filter(([k,v])=>!['year','compareYear','sortBy'].includes(k)&&String(v||'')!=='').length}
async function loadDashboardSafe(){try{await loadDashboard()}catch(e){handleApiError(e)}}
async function loadDashboard(){showLoading(true);try{S.data=await CESApi.call('dashboard',S.token,getFilterState());S.rows=S.data.rows||[];S.dataVersion=String(S.data.dataVersion);renderDashboard();renderEquipment();$('activeFilterCount').textContent=activeFilterCount()+' active';updateAlertCount()}finally{showLoading(false)}}
function updateAlertCount(){const n=(S.data&&S.data.priorityActions||[]).length;$('notificationCount').textContent=n;$('notificationCount').classList.toggle('hidden',!n)}
function renderDashboard(){const d=S.data,k=d.kpi||{};$('kEquip').textContent=(k.equipment||0).toLocaleString();$('kScope').textContent=`${k.sites||0} sites • ${k.vendors||0} vendors`;$('kCurLabel').textContent=`Contract value ${d.year}`;$('kCur').textContent=money(k.currentTotal);$('kYoy').textContent=pct(k.yoy);$('kYoy').className=deltaClass(k.yoy);$('kYoySub').textContent=`${k.comparableRecords||0} like-for-like records`;$('kCoverage').textContent=pct(k.priceCoveragePct);$('kCoverageSub').textContent=`${k.pricedRecords||0}/${k.totalRecords||0} priced`;$('kRiskValue').textContent=money(k.contractAtRisk);$('kIssues').textContent=(k.dataIssues||0).toLocaleString();$('aDefective').textContent=k.defective||0;$('aOld').textContent=k.old8||0;$('aWarranty').textContent=k.warrantyExpiring||0;$('aExpiry').textContent=k.expiring90||0;$('aMissing').textContent=k.missingCurrent||0;renderCharts();renderVendorMovement();renderPriority();renderRecommendations();}
function renderCharts(){const d=S.data;if(typeof Chart==='undefined')return;Object.values(S.charts).forEach(c=>{if(c&&typeof c.destroy==='function')c.destroy()});const years=S.bootstrap.years,top=(d.trend||[]).sort((a,b)=>{const av=(a.byYear[d.year]||0),bv=(b.byYear[d.year]||0);return bv-av}).slice(0,7);S.charts.trend=new Chart($('trendChart'),{type:'line',data:{labels:years,datasets:top.map((v,i)=>({label:v.vendor,data:years.map(y=>v.byYear[y]||null),borderColor:['#0d5ec5','#e23b35','#7a8799','#0b3470','#a5afbd','#496a96','#d6716d'][i%7],backgroundColor:'transparent',tension:.25,spanGaps:true,pointRadius:3}))},options:chartOptions(true)});const sites=(d.siteValues||[]).slice(0,10);S.charts.site=new Chart($('siteChart'),{type:'bar',data:{labels:sites.map(x=>x.site),datasets:[{label:'Contract value',data:sites.map(x=>x.value),backgroundColor:'#0d5ec5'}]},options:chartOptions(false)});const sc=(d.statusCounts||[]);S.charts.status=new Chart($('statusChart'),{type:'doughnut',data:{labels:sc.map(x=>x.status),datasets:[{data:sc.map(x=>x.count),backgroundColor:sc.map(x=>x.status==='Active'?'#19a66a':x.status==='Defective'?'#e23b35':x.status==='Decommission'?'#8a96a8':'#e59618'),borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom',labels:{usePointStyle:true,font:{family:'Prompt',size:10}}}}}})}
function chartOptions(legend){return{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{display:legend,position:'bottom',labels:{usePointStyle:true,font:{family:'Prompt',size:10}}},tooltip:{callbacks:{label:c=>`${c.dataset.label}: ${money(c.raw)}`}}},scales:{x:{grid:{display:false},ticks:{font:{family:'Prompt',size:9}}},y:{beginAtZero:false,grid:{color:'#edf1f6'},ticks:{font:{family:'Prompt',size:9},callback:v=>new Intl.NumberFormat('en',{notation:'compact'}).format(v)}}}}}
function renderVendorMovement(){const rows=(S.data.vendorComparison||[]).slice(0,12);$('vendorMovement').innerHTML=rows.map(x=>`<div class="rank-row"><b>${esc(x.vendor)}</b><span class="value">${money(x.currentValue)}</span><span class="delta ${deltaClass(x.deltaPct)}">${pct(x.deltaPct)}</span><button class="action-btn" data-vendor="${esc(x.vendor)}" title="Compare vendor">${icon('compare')}</button></div>`).join('')||'<div class="muted">No comparable vendor data.</div>'}
function renderPriority(){const rows=S.data.priorityActions||[];$('priorityBody').innerHTML=rows.map(x=>`<tr><td><b>${esc(x.site)}</b></td><td>${esc(x.vendor)}</td><td>${esc(x.equipment)}<br><small class="muted">${esc(x.model)}</small></td><td>${esc(x.nhCode)}</td><td>${money(x.currentPrice)}</td><td class="delta ${deltaClass(x.deltaPct)}">${pct(x.deltaPct)}</td><td>${(x.reasons||[]).map(r=>`<span class="status ${r.severity==='high'?'st-defective':r.severity==='medium'?'st-warranty':'st-other'}">${esc(r.type)}</span>`).join(' ')}</td><td>${actionButton('detail',x.recordId,'Detail','info')}</td></tr>`).join('')||'<tr><td colspan="8" class="muted">No priority alerts for current filters.</td></tr>'}
function renderRecommendations(){const k=S.data.kpi||{},r=[];if((k.priceCoveragePct||0)<.8)r.push({level:'high',title:'Improve yearly price coverage',text:`Current price coverage is ${pct(k.priceCoveragePct)}. Complete missing yearly prices before vendor inflation decisions.`});if((k.expiring90||0)>0)r.push({level:'high',title:'Start renewal action',text:`${k.expiring90} contract records are within the configured expiry window. Prioritize high-value contracts first.`});if((k.warrantyExpiring||0)>0)r.push({level:'medium',title:'Warranty transition review',text:`${k.warrantyExpiring} equipment records are approaching warranty end. Confirm MA coverage and first-year post-warranty price.`});if((k.old8||0)>0)r.push({level:'medium',title:'EOL/EOS replacement planning',text:`${k.old8} equipment records are aged ≥ 8 years. Cross-check EOS/EOL and replacement budget.`});if((k.dataIssues||0)>0)r.push({level:'medium',title:'Close data-quality gaps',text:`${k.dataIssues} records require review. Fix Site, price basis, MA type and contract dates in source sheets.`});if(!r.length)r.push({level:'',title:'Data is in good shape',text:'No major action detected for the current scope and filters.'});$('recommendations').innerHTML=r.slice(0,6).map(x=>`<div class="recommendation ${x.level}"><b>${esc(x.title)}</b><p>${esc(x.text)}</p></div>`).join('')}
function renderEquipment(){const d=S.data;$('rowCount').textContent=`${(d.totalRows||0).toLocaleString()} records`;const rows=S.rows;$('equipmentBody').innerHTML=rows.map(r=>{const wd=daysUntil(r.warrantyDate),ed=daysUntil(r.endDate),warranty=wd===null?'—':wd<0?'Expired':wd<=90?`<span class="status st-warranty">${wd}d</span>`:fmtDate(r.warrantyDate),end=ed===null?'—':ed<0?`<span class="status st-decommission">Expired</span>`:ed<=90?`<span class="status st-defective">${ed}d</span>`:fmtDate(r.endDate);return`<tr><td><b>${esc(r.site)}</b></td><td>${esc(r.hospital)}</td><td>${esc(r.vendor)}</td><td>${esc(r.equipment)}</td><td>${esc(r.model)}</td><td>${esc(r.systemSn||'—')}</td><td><b>${esc(r.nhCode||'—')}</b></td><td>${statusBadge(r.status)}</td><td>${warranty}</td><td>${r.lifetimeYears===null?'—':(Number(r.lifetimeYears)>=8?`<span class="status st-warranty">${num(r.lifetimeYears)}y • EOL/EOS</span>`:num(r.lifetimeYears)+'y')}</td><td>${end}</td>${[2024,2025,2026,2027,2028,2029].map(y=>`<td>${money(r['price'+y])}</td>`).join('')}<td class="delta ${deltaClass(r.deltaPct)}">${pct(r.deltaPct)}</td><td>${esc(r.quality||'—')}</td><td><div class="action-row">${actionButton('detail',r.recordId,'Detail','info')}${actionButton('compare',r.recordId,'Compare','compare')}${r.canEdit?actionButton('edit',r.recordId,'Edit','edit'):''}</div></td></tr>`}).join('')||'<tr><td colspan="20" class="muted">No equipment found.</td></tr>'}
function equipmentAction(e){const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,id=b.dataset.id;if(a==='detail')openDetail(id);else if(a==='edit')openEdit(id);else if(a==='compare')openCompareEquipment(id)}

async function openDetail(id){showLoading(true);try{const d=await CESApi.call('contractDetail',S.token,id),m=d.master;$('detailBody').innerHTML=`<div class="mini-kpis"><div class="mini-kpi"><span>Site</span><b>${esc(m.Site||'—')}</b></div><div class="mini-kpi"><span>Vendor</span><b>${esc(m.Vendor||'—')}</b></div><div class="mini-kpi"><span>NH Code</span><b>${esc(m.NH_Code||'—')}</b></div><div class="mini-kpi"><span>Status</span><b>${esc(m.Status_Canonical||'—')}</b></div></div><div class="profile-form-grid"><div><b>Hospital</b><p>${esc(m.Hospital||'—')}</p></div><div><b>Equipment</b><p>${esc((m.Modality||'')+' '+(m.Model||''))}</p></div><div><b>S/N</b><p>${esc(m.System_SN||'—')}</p></div><div><b>MA Type</b><p>${esc(m.MA_Category||'—')}</p></div><div><b>Warranty</b><p>${fmtDate(m.Warranty_Date)}</p></div><div><b>Contract End</b><p>${fmtDate(m.End_Date)}</p></div></div><h4>Price scenarios</h4><div class="table-scroll"><table><thead><tr><th>Year</th><th>Scenario</th><th>Coverage</th><th>Price type</th><th>Price</th><th>Quality basis</th><th>Source</th></tr></thead><tbody>${(d.scenarios||[]).map(x=>`<tr><td>${x.year||'—'}</td><td>${esc(x.scenario||'—')}</td><td>${esc(x.coverage||'—')}</td><td>${esc(x.priceType||'—')}</td><td>${money(x.price)}</td><td>${esc(x.qualityBasis||'—')}</td><td>${esc(x.sourceSheet||'—')}</td></tr>`).join('')||'<tr><td colspan="7">No scenario records.</td></tr>'}</tbody></table></div>`;$('detailModal').classList.remove('hidden')}catch(e){handleApiError(e)}finally{showLoading(false)}}
function findRow(id){return S.rows.find(r=>r.recordId===id)}
function openEdit(id){const r=findRow(id);if(!r||!r.canEdit)return toast('No edit permission');S.activeEdit=r;$('editRecordId').value=id;$('editIdentity').value=`${r.site} • ${r.vendor} • ${r.nhCode||r.recordId}`;fillYear('editYear',S.bootstrap.years,S.data.year);$('editStatus').value=r.status||'Active';$('editMaCategory').value=r.maType||'Package / Other';$('editStartDate').value=(r.startDate||'').slice(0,10);$('editEndDate').value=(r.endDate||'').slice(0,10);$('editPmYear').value=r.pmYear??'';$('editScenario').value=r.preferredScenario||'';$('editQuality').value=r.quality||'';$('editRemark').value=r.remark||'';$('editSourceNotes').value=r.sourcePriceNotes||'';$('editNote').value='';syncEditPrice();$('editModal').classList.remove('hidden')}
function syncEditPrice(){if(!S.activeEdit)return;$('editPrice').value=S.activeEdit['price'+$('editYear').value]??''}
async function saveEdit(e){e.preventDefault();showLoading(true);try{await CESApi.call('saveOverride',S.token,{recordId:$('editRecordId').value,year:+$('editYear').value,price:+$('editPrice').value,status:$('editStatus').value,maCategory:$('editMaCategory').value,startDate:$('editStartDate').value,endDate:$('editEndDate').value,pmYear:$('editPmYear').value,remark:$('editRemark').value,preferredScenario:$('editScenario').value,priceDataQuality:$('editQuality').value,sourcePriceNotes:$('editSourceNotes').value,note:$('editNote').value});$('editModal').classList.add('hidden');await loadDashboard();toast('Saved to Google Sheet')}catch(e){handleApiError(e)}finally{showLoading(false)}}
async function openCompareEquipment(id){showLoading(true);try{const d=await CESApi.call('compare',S.token,{type:'equipment',recordId:id});showCompare(d)}catch(e){handleApiError(e)}finally{showLoading(false)}}
async function openCompareVendor(vendor){showLoading(true);try{const d=await CESApi.call('compare',S.token,{type:'vendor',vendor,site:$('site').value});showCompare(d)}catch(e){handleApiError(e)}finally{showLoading(false)}}
function showCompare(d){$('compareTitle').textContent='Compare • '+d.title;const years=d.years||[];if(S.charts.compare)S.charts.compare.destroy();if(d.type==='equipment'){S.charts.compare=new Chart($('compareChart'),{type:'line',data:{labels:years,datasets:[{label:'Equipment',data:years.map(y=>d.own[y]),borderColor:'#e23b35',backgroundColor:'transparent',tension:.2},{label:`${d.vendor} aggregate`,data:years.map(y=>d.vendorAggregate[y]),borderColor:'#0d5ec5',backgroundColor:'transparent',tension:.2}]},options:chartOptions(true)});$('compareBody').innerHTML=`<p class="muted">Site ${esc(d.site)} • Vendor aggregate covers ${d.vendorRecords} records.</p>`}else{S.charts.compare=new Chart($('compareChart'),{type:'line',data:{labels:years,datasets:[{label:d.title,data:years.map(y=>d.byYear[y]),borderColor:'#0d5ec5',backgroundColor:'transparent',tension:.2}]},options:chartOptions(true)});$('compareBody').innerHTML=`<div class="table-scroll"><table><thead><tr><th>Site</th><th>Records</th>${years.map(y=>`<th>${y}</th>`).join('')}</tr></thead><tbody>${(d.sites||[]).map(s=>`<tr><td>${esc(s.site)}</td><td>${s.records}</td>${years.map(y=>`<td>${money(s.byYear[y])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}$('compareModal').classList.remove('hidden')}

async function loadSiteContracts(){if(S.page!=='contracts')return;showLoading(true);try{S.contracts=await CESApi.call('siteContracts',S.token,{site:$('contractSite').value,vendor:$('contractVendor').value,year:+$('contractYear').value});S.files=await CESApi.call('contractFiles',S.token,{site:$('contractSite').value,vendor:$('contractVendor').value});renderContracts();renderContractFiles()}catch(e){handleApiError(e)}finally{showLoading(false)}}
function filteredContracts(){const q=$('contractSearch').value.trim().toLowerCase();return(S.contracts||[]).filter(c=>!q||[c.site,c.hospital,c.vendor,c.maType,c.startDate,c.endDate,...(c.records||[]).flatMap(r=>[r.equipment,r.model,r.nhCode])].join(' ').toLowerCase().includes(q))}
function renderContracts(){const rows=filteredContracts(),year=+$('contractYear').value,total=rows.reduce((a,c)=>a+(Number(c.priceYears&&c.priceYears[year])||0),0),equip=rows.reduce((a,c)=>a+c.equipmentCount,0),files=rows.reduce((a,c)=>a+(c.files||[]).length,0);$('contractSummary').innerHTML=`<div class="mini-kpi"><span>Contracts</span><b>${rows.length}</b></div><div class="mini-kpi"><span>Equipment</span><b>${equip}</b></div><div class="mini-kpi"><span>${year} value</span><b>${money(total)}</b></div><div class="mini-kpi"><span>Files</span><b>${files}</b></div>`;$('contractCount').textContent=`${rows.length} contracts`;$('contractBody').innerHTML=rows.map(c=>`<tr><td><b>${esc(c.site)}</b></td><td>${esc(c.hospital)}</td><td>${esc(c.vendor)}</td><td>${esc(c.maType||'—')}</td><td>${fmtDate(c.startDate)} → ${fmtDate(c.endDate)}</td><td>${c.equipmentCount}</td><td><span class="status st-active">${c.active} Active</span> ${c.defective?`<span class="status st-defective">${c.defective} Defective</span>`:''}</td><td>${money(c.priceYears&&c.priceYears[year])}</td><td>${(c.files||[]).length}</td><td><div class="action-row"><button class="action-btn" data-action="upload" data-key="${esc(c.contractKey)}" title="Upload">${icon('upload')}</button><button class="action-btn" data-action="compareVendor" data-vendor="${esc(c.vendor)}" title="Compare vendor">${icon('compare')}</button>${(c.files||[])[0]?`<a class="action-btn" href="${esc(c.files[0].folderUrl)}" target="_blank" title="Open folder">${icon('folder')}</a>`:''}</div></td></tr>`).join('')||'<tr><td colspan="10" class="muted">No contract groups found.</td></tr>'}
function contractAction(e){const b=e.target.closest('[data-action]');if(!b)return;if(b.dataset.action==='compareVendor')return openCompareVendor(b.dataset.vendor);if(b.dataset.action==='upload'){const c=S.contracts.find(x=>x.contractKey===b.dataset.key);openUpload(c)}}
function renderContractFiles(){const files=S.files||[];$('contractFiles').innerHTML=files.map(f=>`<div class="file-card"><div class="file-icon">${icon('contract')}</div><div class="file-meta"><b>${esc(f.fileName)}</b><small>${esc(f.site)} • ${esc(f.vendor||'—')} • ${fmtDateTime(f.uploadedAt)}</small><small>${esc(f.contractName||'')}</small><div class="file-actions"><a class="secondary compact" href="${esc(f.driveUrl)}" target="_blank">Open File</a><a class="ghost compact" href="${esc(f.folderUrl)}" target="_blank">Folder</a></div></div></div>`).join('')||'<div class="muted">No uploaded contract files in current scope.</div>'}
function openUpload(c){const site=c?.site||$('contractSite').value||S.profile.allowedSites?.[0]||'';$('uSite').value=site;$('uVendor').value=c?.vendor||$('contractVendor').value||'';$('uContractName').value=c?`${c.site} - ${c.vendor} - ${c.maType||'Contract'} - ${c.startDate||''} to ${c.endDate||''}`:'';$('uRecordId').value=c?.records?.[0]?.recordId||'';$('uHospital').value=c?.hospital||'';$('uGroup').value=c?.group||'';$('uNotes').value='';$('uploadModal').classList.remove('hidden')}
async function startUpload(e){e.preventDefault();showLoading(true);try{const r=await CESApi.call('createUploadTicket',S.token,{site:$('uSite').value,vendor:$('uVendor').value,contractName:$('uContractName').value,recordId:$('uRecordId').value,hospital:$('uHospital').value,group:$('uGroup').value,notes:$('uNotes').value});$('uploadModal').classList.add('hidden');const w=window.open(r.url,'CESContractUpload','width=720,height=760,resizable=yes,scrollbars=yes');if(!w)throw new Error('Popup blocked. Please allow popups for this site.')}catch(e){handleApiError(e)}finally{showLoading(false)}}

async function loadUsers(){if(!S.profile.canManageAccess)return;showLoading(true);try{S.staff=await CESApi.call('getStaffAccess',S.token);renderUserSummary();renderUsers()}catch(e){handleApiError(e)}finally{showLoading(false)}}
function renderUserSummary(){const total=S.staff.length,active=S.staff.filter(x=>x.isActive).length,edit=S.staff.filter(x=>x.canEditData).length,emails=S.staff.filter(x=>x.email).length;$('roleSummary').innerHTML=`<div class="mini-kpi"><span>Users in scope</span><b>${total}</b></div><div class="mini-kpi"><span>Active</span><b class="good">${active}</b></div><div class="mini-kpi"><span>Edit access</span><b>${edit}</b></div><div class="mini-kpi"><span>Profile email complete</span><b>${emails}</b></div>`}
function renderUsers(){const q=$('staffSearch').value.trim().toLowerCase(),rows=S.staff.filter(x=>!q||[x.staffId,x.thName,x.engName,x.email,x.position,x.role,x.allowedSite,x.allowedGroup].join(' ').toLowerCase().includes(q));$('staffBody').innerHTML=rows.map(x=>`<tr><td><b>${esc(x.staffId)}</b></td><td>${esc(x.engName||x.thName||x.staffName||'—')}<br><small class="muted">${esc(x.thName||'')}</small></td><td>${esc(x.email||'—')}</td><td>${esc(x.position||'—')}</td><td>${esc(x.role)}</td><td>${esc(x.allowedSite||'—')}<br><small class="muted">${esc(x.allowedGroup||'')}</small></td><td>${x.canEditData?'<span class="status st-active">Yes</span>':'<span class="status st-decommission">No</span>'}</td><td>${x.isActive?'<span class="status st-active">Active</span>':'<span class="status st-defective">Inactive</span>'}</td><td><button class="action-btn" data-user="${esc(x.staffId)}">${icon('edit')}</button></td></tr>`).join('')||'<tr><td colspan="9">No users.</td></tr>'}
function openUserModal(id){const x=id?S.staff.find(s=>s.staffId===id):null;$('userModalTitle').textContent=x?'Edit User':'Add User';$('aStaffId').value=x?.staffId||'';$('aStaffId').disabled=!!x;$('aRole').value=x?.role||'STAFF';$('aThName').value=x?.thName||x?.staffName||'';$('aEngName').value=x?.engName||'';$('aEmail').value=x?.email||'';$('aPosition').value=x?.position||'';$('aTelephone').value=x?.telephone||'';$('aProfileSite').value=x?.profileSite||'';$('aProfileGroup').value=x?.profileGroup||'';$('aSite').value=x?.allowedSite||(S.profile.allowedSites?.[0]||'');$('aGroup').value=x?.allowedGroup||(S.profile.allowedGroups?.[0]||'');$('aActive').value=x?.isActive?'1':'1';$('aViewAll').value=x?.canViewAllSites?'1':'0';$('aEdit').value=x?.canEditData?'1':'0';$('aNotes').value=x?.notes||'';$('aViewAll').disabled=!S.profile.isFullAdmin;$('userModal').classList.remove('hidden')}
async function saveUser(e){e.preventDefault();showLoading(true);const id=$('aStaffId').value.trim(),th=$('aThName').value.trim(),eng=$('aEngName').value.trim();try{await CESApi.call('saveStaffAccess',S.token,{staffId:id,staffName:th||eng||id,role:$('aRole').value,allowedSite:$('aSite').value,allowedGroup:$('aGroup').value,isActive:$('aActive').value==='1',canViewAllSites:$('aViewAll').value==='1',canEditData:$('aEdit').value==='1',notes:$('aNotes').value});await CESApi.call('saveMyProfile',S.token,{userId:id,thName:th,engName:eng,email:$('aEmail').value,position:$('aPosition').value,telephone:$('aTelephone').value,site:$('aProfileSite').value||$('aSite').value,group:$('aProfileGroup').value||$('aGroup').value});$('userModal').classList.add('hidden');await loadUsers();toast('User profile and permission saved')}catch(e){handleApiError(e)}finally{$('aStaffId').disabled=false;showLoading(false)}}
function exportUsers(){exportXlsx('CES_User_Management',[['User ID','Thai Name','English Name','Email','Position','Role','Allowed Site','Allowed Group','Edit','Active'],...S.staff.map(x=>[x.staffId,x.thName,x.engName,x.email,x.position,x.role,x.allowedSite,x.allowedGroup,x.canEditData?'Y':'N',x.isActive?'Y':'N'])])}

function openProfile(){$('profileMenu').classList.add('hidden');const p=S.profile;$('pUserId').value=p.staffId||'';$('pRole').value=p.role||'';$('pEngName').value=p.engName||'';$('pThName').value=p.thName||'';$('pEmail').value=p.email||'';$('pPosition').value=p.position||'';$('pTelephone').value=p.telephone||'';$('pSite').value=p.profileSite||p.allowedSites?.[0]||'';$('pGroup').value=p.profileGroup||p.allowedGroups?.[0]||'';$('pViewScope').textContent=p.canViewAllSites?'All Sites':(p.allowedSites||[]).join(', ')||'Group scope';$('pEditPermission').textContent=p.canEditData?'Allowed':'Read only';$('profileModal').classList.remove('hidden')}
async function saveProfile(e){e.preventDefault();showLoading(true);try{S.profile=await CESApi.call('saveMyProfile',S.token,{userId:S.profile.staffId,engName:$('pEngName').value,thName:$('pThName').value,email:$('pEmail').value,position:$('pPosition').value,telephone:$('pTelephone').value,site:$('pSite').value,group:$('pGroup').value});updateProfileUi();$('profileModal').classList.add('hidden');toast('Profile saved')}catch(e){handleApiError(e)}finally{showLoading(false)}}
function updateProfileUi(){const p=S.profile||{},name=p.engName||p.thName||p.staffName||p.staffId||'User';$('profileName').textContent=name;$('profileRole').textContent=p.position||p.role||'';$('profileInitial').textContent=initialOf(name);$('scopePill').textContent=p.canViewAllSites?'All sites':(p.allowedSites||[]).join(', ')||'Scoped';}

async function loadSettings(){showLoading(true);try{const [settings,notify]=await Promise.all([CESApi.call('settings',S.token),CESApi.call('getNotificationConfig',S.token)]);S.settings=settings;S.notifyConfig=notify;renderSettings();renderNotificationConfig()}catch(e){handleApiError(e)}finally{showLoading(false)}}
function renderSettings(){const x=S.settings,a=x.alerts||{},h=x.systemHealth||{},allowed=[5,10,15,30,60,120],local=Number(localStorage.getItem('ces_sync_sec')||x.autoSyncSec||5);$('notifySettingsCard').classList.toggle('hidden',!['ADMIN','MANAGER'].includes(S.profile.role));$('runNotifyNowBtn').classList.toggle('hidden',!['ADMIN','MANAGER'].includes(S.profile.role));$('localSyncSec').value=String(allowed.includes(local)?local:5);$('syncModeLabel').textContent=(allowed.includes(local)?local:5)+' sec';$('sDataVersion').textContent=String(x.dataVersion);$('sLastChange').textContent=fmtDateTime(x.lastSheetChangeAt);$('sLastRebuild').textContent=fmtDateTime(x.lastRebuildAt);$('sChangeSource').value=x.lastSheetChangeSource||'—';$('sServerSync').value=String(allowed.includes(Number(x.autoSyncSec))?x.autoSyncSec:5);fillYear('sDefaultYear',S.bootstrap.years,x.defaultYear);fillYear('sCompareYear',S.bootstrap.years,x.defaultCompareYear);$('alertEnabled').value=a.enabled?'1':'0';$('alertIncreasePct').value=a.priceIncreasePct??10;$('alertDecreasePct').value=a.priceDecreasePct??5;$('alertWarrantyDays').value=a.warrantyDays??90;$('alertExpiryDays').value=a.expiryDays??90;$('alertAgeYears').value=a.ageYears??8;$('alertMinValue').value=a.minContractValue??0;$('alertMissingPrice').value=a.missingPrice?'1':'0';$('alertDefective').value=a.defective?'1':'0';$('alertDataQuality').value=a.dataQuality?'1':'0';$('alertStatusBadge').textContent=a.enabled?'ACTIVE':'DISABLED';$('alertStatusBadge').className='status-badge '+(a.enabled?'green':'');$('sSheetId').textContent=x.spreadsheetId;$('sWebApp').textContent=x.webAppUrl||window.CES_CONFIG.webAppUrl;$('sTimezone').textContent=x.timeZone;$('openSheetBtn').href=x.spreadsheetUrl;$('settingsDriveBtn').href=x.contractFolderUrl||window.CES_CONFIG.contractDriveUrl;[['hEquipmentRows',h.equipmentRows],['hPriceRows',h.priceRows],['hDashboardRows',h.dashboardRows],['hActiveStaff',h.activeStaff],['hVendorSheets',h.vendorSheets]].forEach(([id,v])=>$(id).textContent=(v??'—').toLocaleString?.()||v||'—');$('sWatcher').textContent=fmtDateTime(x.lastWatcherAt);const edit=!!x.canEditSettings;['sDefaultYear','sCompareYear','sServerSync','saveSettingsBtn','alertEnabled','alertIncreasePct','alertDecreasePct','alertWarrantyDays','alertExpiryDays','alertAgeYears','alertMinValue','alertMissingPrice','alertDefective','alertDataQuality','saveAlertSettingsBtn'].forEach(id=>$(id).disabled=!edit);$('rebuildBtn').disabled=!S.profile.isFullAdmin}
async function saveSettings(){showLoading(true);try{S.settings=await CESApi.call('saveSettings',S.token,{defaultYear:+$('sDefaultYear').value,defaultCompareYear:+$('sCompareYear').value,autoSyncSec:+$('sServerSync').value,alerts:{enabled:$('alertEnabled').value==='1',priceIncreasePct:+$('alertIncreasePct').value,priceDecreasePct:+$('alertDecreasePct').value,warrantyDays:+$('alertWarrantyDays').value,expiryDays:+$('alertExpiryDays').value,ageYears:+$('alertAgeYears').value,minContractValue:+$('alertMinValue').value,missingPrice:$('alertMissingPrice').value==='1',defective:$('alertDefective').value==='1',dataQuality:$('alertDataQuality').value==='1'}});renderSettings();await loadBootstrap(true);await loadDashboard();toast('Settings saved')}catch(e){handleApiError(e)}finally{showLoading(false)}}
function renderNotificationConfig(){$('notifyConfigBody').innerHTML=(S.notifyConfig||[]).map(x=>`<tr><td><b>${esc(x.site)}</b><br><small class="muted">${esc(x.hospital||'')}</small></td><td>${esc(x.managerStaffId||'—')}</td><td>${esc(x.toEmail||'—')}</td><td>${esc(x.ccEmail||'—')}</td><td>${x.warrantyDays}d</td><td>${x.contractDays}d</td><td>${x.eolAgeYears}y</td><td>${esc(x.frequency)}</td><td>${String(x.sendHour).padStart(2,'0')}:00</td><td>${x.enabled?'<span class="status st-active">Active</span>':'<span class="status st-decommission">Off</span>'}</td><td><div class="action-row">${x.canEdit?`<button class="action-btn" data-notify="edit" data-site="${esc(x.site)}">${icon('edit')}</button><button class="action-btn" data-notify="test" data-site="${esc(x.site)}">${icon('bell')}</button>`:''}</div></td></tr>`).join('')||'<tr><td colspan="10">No notification configuration.</td></tr>'}
function notificationConfigAction(e){const b=e.target.closest('[data-notify]');if(!b)return;if(b.dataset.notify==='edit')openNotificationModal(b.dataset.site);else if(b.dataset.notify==='test')sendTestForSite(b.dataset.site)}
function openNotificationModal(site){const x=S.notifyConfig.find(n=>n.site===site);if(!x)return;$('nSite').value=x.site;$('nHospital').value=x.hospital||'';$('nGroup').value=x.group||'';$('nManagerId').value=x.managerStaffId||'';$('nTo').value=x.toEmail||'';$('nCc').value=x.ccEmail||'';$('nWarranty').value=x.warrantyDays;$('nContract').value=x.contractDays;$('nEol').value=x.eolAgeYears;$('nFrequency').value=x.frequency;$('nHour').value=x.sendHour;$('nDefective').value=x.notifyDefective?'1':'0';$('nEnabled').value=x.enabled?'1':'0';$('notifyModal').classList.remove('hidden')}
async function saveNotificationConfig(e){e.preventDefault();showLoading(true);try{await CESApi.call('saveNotificationConfig',S.token,{site:$('nSite').value,hospital:$('nHospital').value,group:$('nGroup').value,managerStaffId:$('nManagerId').value,toEmail:$('nTo').value,ccEmail:$('nCc').value,warrantyDays:+$('nWarranty').value,contractDays:+$('nContract').value,eolAgeYears:+$('nEol').value,frequency:$('nFrequency').value,sendHour:+$('nHour').value,notifyDefective:$('nDefective').value==='1',enabled:$('nEnabled').value==='1'});$('notifyModal').classList.add('hidden');await loadSettings();toast('Notification config saved')}catch(e){handleApiError(e)}finally{showLoading(false)}}
async function testNotification(){return sendTestForSite($('nSite').value)}
async function sendTestForSite(site){showLoading(true);try{await CESApi.call('sendTestNotification',S.token,site);toast('Test email sent')}catch(e){handleApiError(e)}finally{showLoading(false)}}
async function runNotificationNow(){showLoading(true);try{const r=await CESApi.call('runNotificationNow',S.token,'');toast(`Notification run complete • ${r.filter(x=>x.sent).length} site(s) sent`)}catch(e){handleApiError(e)}finally{showLoading(false)}}
async function viewReadiness(){showLoading(true);try{const r=await CESApi.call('readiness',S.token);alert(r.map(x=>`${x.status} | ${x.check}: ${x.value}\n${x.note||''}`).join('\n\n'))}catch(e){handleApiError(e)}finally{showLoading(false)}}
async function rebuildData(){if(!S.profile.isFullAdmin)return toast('Full Admin only');if(!confirm('Rebuild standardized data now? Raw vendor sheets are preserved.'))return;showLoading(true);try{await CESApi.call('adminRebuild',S.token);await refreshAll();toast('Rebuild completed')}catch(e){handleApiError(e)}finally{showLoading(false)}}

function openAlertCenter(){const p=S.data?.priorityActions||[];$('alertCenter').innerHTML=`<div class="mini-kpis"><div class="mini-kpi"><span>Priority alerts</span><b>${p.length}</b></div><div class="mini-kpi"><span>Defective</span><b>${S.data?.kpi?.defective||0}</b></div><div class="mini-kpi"><span>Warranty</span><b>${S.data?.kpi?.warrantyExpiring||0}</b></div><div class="mini-kpi"><span>Contract expiry</span><b>${S.data?.kpi?.expiring90||0}</b></div></div><div class="table-scroll"><table><thead><tr><th>Site</th><th>Vendor</th><th>Equipment</th><th>NH Code</th><th>Reason</th></tr></thead><tbody>${p.map(x=>`<tr><td>${esc(x.site)}</td><td>${esc(x.vendor)}</td><td>${esc(x.equipment)} ${esc(x.model)}</td><td>${esc(x.nhCode)}</td><td>${(x.reasons||[]).map(r=>esc(r.type)).join(', ')}</td></tr>`).join('')}</tbody></table></div>`;$('alertModal').classList.remove('hidden')}
function handleCommand(cmd){if(cmd==='sync')checkSync(true);else if(cmd==='notify')openAlertCenter();else if(cmd==='reset')resetFilters();else if(cmd==='excel')exportEquipment();else if(cmd==='pdf')window.print()}
function handleExport(type){if(type==='contracts-excel')exportContracts();else if(type==='contracts-pdf')window.print()}
function exportXlsx(name,rows){if(window.XLSX){const wb=XLSX.utils.book_new(),ws=XLSX.utils.aoa_to_sheet(rows);XLSX.utils.book_append_sheet(wb,ws,'Data');XLSX.writeFile(wb,`${name}_${new Date().toISOString().slice(0,10)}.xlsx`);return}const csv='\ufeff'+rows.map(a=>a.map(csvCell).join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=name+'.csv';a.click();URL.revokeObjectURL(a.href)}
function exportEquipment(){const h=['Site','Hospital','Group','Vendor','Equipment','Model','S/N','NH Code','Status','Warranty','Lifetime','Contract Start','Contract End','PM/Year','2024','2025','2026','2027','2028','2029','Change %','Quality','Source','Remark'];const rows=S.rows.map(r=>[r.site,r.hospital,r.group,r.vendor,r.equipment,r.model,r.systemSn,r.nhCode,r.status,r.warrantyDate,r.lifetimeYears,r.startDate,r.endDate,r.pmYear,r.price2024,r.price2025,r.price2026,r.price2027,r.price2028,r.price2029,r.deltaPct===null?'':r.deltaPct*100,r.quality,r.sourceSheet,r.remark]);exportXlsx('CES_Equipment_Contract',[h,...rows])}
function exportContracts(){const y=+$('contractYear').value,h=['Site','Hospital','Vendor','MA Type','Start','End','Equipment','Active','Defective',`${y} Value`,'File Count'];exportXlsx('CES_Site_Contracts',[h,...filteredContracts().map(c=>[c.site,c.hospital,c.vendor,c.maType,c.startDate,c.endDate,c.equipmentCount,c.active,c.defective,c.priceYears?.[y]||'',c.files?.length||0])])}

function globalSearchChanged(){const q=$('globalSearch').value;if(S.page==='contracts'){$('contractSearch').value=q;renderContracts()}else if(S.page==='users'){$('staffSearch').value=q;renderUsers()}else{$('search').value=q;clearTimeout(globalSearchChanged.t);globalSearchChanged.t=setTimeout(loadDashboardSafe,280)}}
function switchPage(page){if(page==='users'&&!S.profile.canManageAccess)return;S.page=page;document.querySelectorAll('.page-view').forEach(p=>p.classList.remove('active'));$(`page-${page}`).classList.add('active');document.querySelectorAll('.nav-btn[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const m={dashboard:['PRICE INTELLIGENCE','Dashboard','Executive contract price, risk and data-quality overview.'],contracts:['CONTRACT MANAGEMENT','Site Contract Detail','Contract-level summary, files, renewals and Site actions.'],equipment:['ASSET DETAIL','Equipment','Equipment-level contract price, warranty, status and comparison.'],users:['ACCESS CONTROL','User Management','User profile, role and Site permission.'],settings:['SYSTEM','Setting','Live sync, alert, notification and data configuration.']};$('pageEyebrow').textContent=m[page][0];$('pageTitle').textContent=m[page][1];$('pageSubtitle').textContent=m[page][2];$('dataToolbar').classList.toggle('hidden',!['dashboard','equipment'].includes(page));if(page==='contracts')loadSiteContracts();if(page==='users')loadUsers();if(page==='settings')loadSettings();$('sidebar').classList.remove('mobile-open')}
async function refreshAll(){showLoading(true);try{await loadBootstrap(true);await loadDashboard();if(S.page==='contracts')await loadSiteContracts();if(S.page==='users')await loadUsers();if(S.page==='settings')await loadSettings();toast('Data synchronized')}catch(e){handleApiError(e)}finally{showLoading(false)}}
function getSyncSec(){const n=Number(localStorage.getItem('ces_sync_sec')||S.bootstrap?.defaults?.autoSyncSec||5);return[5,10,15,30,60,120].includes(n)?n:5}
function startAutoSync(){clearInterval(S.syncTimer);const sec=getSyncSec();setSyncState('Live sync',`Every ${sec} sec`,'green');S.syncTimer=setInterval(()=>{if(!document.hidden)checkSync(false)},sec*1000)}
async function checkSync(force){if(!S.token)return;setSyncState('Checking…','Google Sheet','orange');try{const r=await CESApi.call('syncStatus',S.token,S.dataVersion);S.profile=r.profile||S.profile;updateProfileUi();$('userNav').classList.toggle('hidden',!S.profile.canManageAccess);if(r.changed){S.dataVersion=String(r.dataVersion);await loadBootstrap(true);await loadDashboard();if(S.page==='contracts')await loadSiteContracts();if(S.page==='users')await loadUsers();if(S.page==='settings')await loadSettings();toast('Sheet changed • synchronized')}setSyncState('Live sync',`Every ${getSyncSec()} sec`,'green')}catch(e){setSyncState('Sync issue','Click sync','red');if(force)toast(errMsg(e));console.warn(e)}}
function handleApiError(e){const msg=errMsg(e);if(/session/i.test(msg)){sessionStorage.removeItem('ces_token');alert(msg);location.reload();return}toast(msg)}
boot();
